##
#
##
name: vdb

networks:
  net:
    driver: bridge

services:

  chroma:
    image: chromadb/chroma
    restart: always
    ports:
      - 8000:8000
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
    volumes:
      - ${PWD}/dockerdata/chroma:/chroma/chroma
    networks:
      net:

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    #container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    environment:
      - QDRANT__TELEMETRY_DISABLED=TRUE
    volumes:
      - ${PWD}/dockerdata/qdrant:/qdrant/storage
    networks:
      net:

  pgdb:
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ${PWD}/dockerdata/pgdb:/var/lib/postgresql/data
    ports:
      - 55432:5432
    networks:
      net:
        aliases: 
          - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 55433:8080
    networks:
      net: